export const EXTENDED_CATEGORIES = [
  "Accountancy", "Acoustics", "Aerospace Engineering", "Aging and Gerontology", "AgriTech", "Alternative Medicine", "Animation", "Anthropology", "Antiques", "Apiculture (Beekeeping)",
  "Apparel and Fashion", "Archaeology", "Architecture", "Artificial Intelligence", "Assisted Living", "Astrology", "Astronomy", "Automation", "Automotive", "Aviation",
  "B2B Software", "Baking", "Banking", "Beauty and Cosmetics", "Behavioral Economics", "Bioinformatics", "Biometrics", "Biotechnology", "Blockchain", "Board Games",
  "Botany", "Brewing", "Broadcasting", "Building Materials", "Business Intelligence", "Calligraphy", "Cannabis Industry", "Carbon Capture", "Carpentry", "Cartography",
  "Catering", "Ceramics", "Chemistry", "Childcare", "Cinematography", "Civic Tech", "Civil Engineering", "Clean Energy", "Climate Tech", "Cloud Computing",
  "Coffee", "Cognitive Science", "Collectibles", "Commercial Real Estate", "Community Building", "Computer Vision", "Construction Tech", "Consumer Electronics", "Content Creation", "Cosplay",
  "Crafting", "Cryptocurrency", "Cybersecurity", "Data Analytics", "Data Privacy", "Dating Apps", "DeFi (Decentralized Finance)", "Dentistry", "Design Systems", "Digital Art",
  "Digital Marketing", "Drone Technology", "E-commerce", "E-learning", "Early Childhood Education", "Earth Sciences", "Ecology", "EdTech", "Electrical Engineering", "Embedded Systems",
  "Emergency Management", "Employee Wellness", "Energy Storage", "Entertainment", "Entomology", "Environmental Tech", "Ergonomics", "Esports", "Event Management", "Exospace",
  "Fantasy Sports", "Farming", "Fashion Tech", "Feminology", "Film Production", "FinTech", "Fitness Tech", "Food Delivery", "Food Science", "Forestry",
  "Franchising", "Freelance Economy", "Furniture Design", "Game Development", "Genealogy", "Genetics", "Geology", "Geopolitics", "Golf", "Graphic Design",
  "Green Building", "Hardware", "HealthTech", "Heavy Machinery", "History", "Home Automation", "Home Decor", "Homeopathy", "Horticulture", "Hospitality",
  "HR Tech", "Hydrology", "Illustration", "Immigration Tech", "Industrial Design", "Information Security", "Insurance Tech (InsurTech)", "Interior Design", "Internet of Things (IoT)", "Investment Banking",
  "Journalism", "K-12 Education", "Kinesiology", "Landscaping", "Language Learning", "Law and Tech (LegalTech)", "Leatherworking", "Library Science", "Linguistics", "Logistics",
  "Machine Learning", "Macroeconomics", "Magic and Illusion", "Manufacturing", "Mapping Technologies", "Marine Biology", "Marine Engineering", "Market Research", "Marketing Trends", "Martial Arts",
  "Materials Science", "Mathematics", "Mechanical Engineering", "Media and Broadcasting", "Medical Devices", "Mental Health Tech", "Metalsmithing", "Microbiology", "Microscopy", "Military Tech",
  "Mining", "Mobile App Development", "Molecular Biology", "Motorcycles", "Music Production", "Music Tech", "Nanotechnology", "Neuroscience", "No-Code/Low-Code", "Nonprofit Management",
  "Nuclear Energy", "Nutrition", "Oceanography", "Online Communities", "Open Source Software", "Optics", "Optometry", "Organic Farming", "Origami", "Orthopedics",
  "Outdoors and Hiking", "Packaging", "Painting", "Paleontology", "Papercraft", "Parenting", "Parks and Recreation", "Pediatrics", "Perfume & Fragrance", "Personal Finance",
  "Pet Tech", "Pharmacy", "Philanthropy", "Photography", "Physical Therapy", "Physics", "Podcasting", "Political Science", "Polymer Chemistry", "Poultry Farming",
  "Preservation", "Printmaking", "Product Management", "PropTech", "Psychiatry", "Psychology", "Public Health", "Public Relations", "Public Transit", "Publishing",
  "Quantum Computing", "Real Estate", "Renewable Energy", "Retail Tech", "Robotics", "SaaS (Software as a Service)", "SalesTech", "Sculpture", "Search Engine Optimization (SEO)", "Semiconductors",
  "Smart Cities", "Social Media", "Sociology", "Software Engineering", "Solar Energy", "SpaceTech", "Sports Analytics", "Sports Equipment", "Startup Ideas", "Statistics",
  "Streetwear", "Supply Chain", "Sustainability", "Tabletop RPGs", "Tailoring", "Tattooing", "Taxidermy", "Taxonomy", "Tech Gadgets", "Telecommunications",
  "Telehealth", "Textile Design", "Theater", "Theology", "3D Printing", "Topography", "Toxicology", "Toys and Games", "Translation Services", "Travel Tech",
  "Typography", "UI/UX Design", "Urban Farming", "Urban Planning", "Venture Capital", "Veterinary Medicine", "Video Production", "Virtual Reality (VR)", "Vlogging", "Vocal Coaching",
  "Volcanology", "Waste Management", "Watchmaking", "Water Treatment", "Wealth Management", "Web Development", "Web3", "Wedding Planning", "Welding", "Wellness",
  "Wildlife Conservation", "Wind Energy", "Woodworking", "Writing and Editing", "Yoga", "Zoology"
];
